title: Amanda Park
baseURL: https://amanda-park.com
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 10
enableRobotsTXT: yes
enableEmoji: true
languages:
  en:
    contentDir: content/en
    title: Amanda Park
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  background_color_class: bg-black
  description: Storyteller for data, blog posts, and video games.
  facebook: ''
  favicon: ''
  featured_image: /images/dice.jpg
  github: 'https://github.com/amanda-park'
  gitlab: ''
  instagram: ''
  linkedin: 'https://www.linkedin.com/in/parkamanda/'
  mastodon: ''
  recent_posts_number: 3
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: 
  youtube: ''
  show_reading_time: true
permalinks:
  post: "/:year/:month/:day/:slug/"
